# Generated by Django 4.1.3 on 2023-12-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='label',
            new_name='description',
        ),
    ]
